name: Build and deploy to GitHub Pages

on:
  push:
    branches: 
      - main

jobs:
  build-deploy:

    name: Build and deploy
    runs-on: ubuntu-latest
    env: 
      CABAL_VERSION: '3.6'
      GHC_VERSION: '8.10.7'

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{env.GHC_VERSION}}
        cabal-version: ${{env.CABAL_VERSION}}
    - name: 'Run actions/cache@v1: cache cabal store'
      uses: actions/cache@v1
      with:
        path: ~/.cabal/store
        key: cabal-store-${{ runner.OS }}-${{ env.GHC_VERSION }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          cabal-store-${{ runner.OS }}-${{ env.GHC_VERSION }}-
          cabal-store-${{ runner.OS }}-
    - run: cabal update
    - run: cabal build --only-dependencies
    - run: cabal build
    - run: cabal exec site build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: _site